<?php
/**
 * ReturnViewModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ReturnViewModel Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReturnViewModel implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'merchant_reference' => 'string',
        'order_reference' => 'string',
        'channel_return_no' => 'string',
        'status' => 'int',
        'reason' => 'int',
        'customer_comment' => 'string',
        'merchant_comment' => 'string',
        'refund_incl_vat' => 'double',
        'refund_excl_vat' => 'double',
        'lines' => '\Swagger\Client\Model\ReturnLineViewModel[]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'merchant_reference' => 'MerchantReference',
        'order_reference' => 'OrderReference',
        'channel_return_no' => 'ChannelReturnNo',
        'status' => 'Status',
        'reason' => 'Reason',
        'customer_comment' => 'CustomerComment',
        'merchant_comment' => 'MerchantComment',
        'refund_incl_vat' => 'RefundInclVat',
        'refund_excl_vat' => 'RefundExclVat',
        'lines' => 'Lines'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'merchant_reference' => 'setMerchantReference',
        'order_reference' => 'setOrderReference',
        'channel_return_no' => 'setChannelReturnNo',
        'status' => 'setStatus',
        'reason' => 'setReason',
        'customer_comment' => 'setCustomerComment',
        'merchant_comment' => 'setMerchantComment',
        'refund_incl_vat' => 'setRefundInclVat',
        'refund_excl_vat' => 'setRefundExclVat',
        'lines' => 'setLines'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'merchant_reference' => 'getMerchantReference',
        'order_reference' => 'getOrderReference',
        'channel_return_no' => 'getChannelReturnNo',
        'status' => 'getStatus',
        'reason' => 'getReason',
        'customer_comment' => 'getCustomerComment',
        'merchant_comment' => 'getMerchantComment',
        'refund_incl_vat' => 'getRefundInclVat',
        'refund_excl_vat' => 'getRefundExclVat',
        'lines' => 'getLines'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $merchant_reference 
      * @var string
      */
    protected $merchant_reference;
    
    /**
      * $order_reference 
      * @var string
      */
    protected $order_reference;
    
    /**
      * $channel_return_no 
      * @var string
      */
    protected $channel_return_no;
    
    /**
      * $status 
      * @var int
      */
    protected $status;
    
    /**
      * $reason 
      * @var int
      */
    protected $reason;
    
    /**
      * $customer_comment 
      * @var string
      */
    protected $customer_comment;
    
    /**
      * $merchant_comment 
      * @var string
      */
    protected $merchant_comment;
    
    /**
      * $refund_incl_vat 
      * @var double
      */
    protected $refund_incl_vat;
    
    /**
      * $refund_excl_vat 
      * @var double
      */
    protected $refund_excl_vat;
    
    /**
      * $lines 
      * @var \Swagger\Client\Model\ReturnLineViewModel[]
      */
    protected $lines;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->merchant_reference = $data["merchant_reference"];
            $this->order_reference = $data["order_reference"];
            $this->channel_return_no = $data["channel_return_no"];
            $this->status = $data["status"];
            $this->reason = $data["reason"];
            $this->customer_comment = $data["customer_comment"];
            $this->merchant_comment = $data["merchant_comment"];
            $this->refund_incl_vat = $data["refund_incl_vat"];
            $this->refund_excl_vat = $data["refund_excl_vat"];
            $this->lines = $data["lines"];
        }
    }
    
    /**
     * Gets merchant_reference
     * @return string
     */
    public function getMerchantReference()
    {
        return $this->merchant_reference;
    }
  
    /**
     * Sets merchant_reference
     * @param string $merchant_reference 
     * @return $this
     */
    public function setMerchantReference($merchant_reference)
    {
        
        $this->merchant_reference = $merchant_reference;
        return $this;
    }
    
    /**
     * Gets order_reference
     * @return string
     */
    public function getOrderReference()
    {
        return $this->order_reference;
    }
  
    /**
     * Sets order_reference
     * @param string $order_reference 
     * @return $this
     */
    public function setOrderReference($order_reference)
    {
        
        $this->order_reference = $order_reference;
        return $this;
    }
    
    /**
     * Gets channel_return_no
     * @return string
     */
    public function getChannelReturnNo()
    {
        return $this->channel_return_no;
    }
  
    /**
     * Sets channel_return_no
     * @param string $channel_return_no 
     * @return $this
     */
    public function setChannelReturnNo($channel_return_no)
    {
        
        $this->channel_return_no = $channel_return_no;
        return $this;
    }
    
    /**
     * Gets status
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }
  
    /**
     * Sets status
     * @param int $status 
     * @return $this
     */
    public function setStatus($status)
    {
        $allowed_values = array("0", "1", "2", "5");
        if (!in_array($status, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'status', must be one of '0', '1', '2', '5'");
        }
        $this->status = $status;
        return $this;
    }
    
    /**
     * Gets reason
     * @return int
     */
    public function getReason()
    {
        return $this->reason;
    }
  
    /**
     * Sets reason
     * @param int $reason 
     * @return $this
     */
    public function setReason($reason)
    {
        $allowed_values = array("0", "1", "4", "5", "6", "7", "99");
        if (!in_array($reason, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'reason', must be one of '0', '1', '4', '5', '6', '7', '99'");
        }
        $this->reason = $reason;
        return $this;
    }
    
    /**
     * Gets customer_comment
     * @return string
     */
    public function getCustomerComment()
    {
        return $this->customer_comment;
    }
  
    /**
     * Sets customer_comment
     * @param string $customer_comment 
     * @return $this
     */
    public function setCustomerComment($customer_comment)
    {
        
        $this->customer_comment = $customer_comment;
        return $this;
    }
    
    /**
     * Gets merchant_comment
     * @return string
     */
    public function getMerchantComment()
    {
        return $this->merchant_comment;
    }
  
    /**
     * Sets merchant_comment
     * @param string $merchant_comment 
     * @return $this
     */
    public function setMerchantComment($merchant_comment)
    {
        
        $this->merchant_comment = $merchant_comment;
        return $this;
    }
    
    /**
     * Gets refund_incl_vat
     * @return double
     */
    public function getRefundInclVat()
    {
        return $this->refund_incl_vat;
    }
  
    /**
     * Sets refund_incl_vat
     * @param double $refund_incl_vat 
     * @return $this
     */
    public function setRefundInclVat($refund_incl_vat)
    {
        
        $this->refund_incl_vat = $refund_incl_vat;
        return $this;
    }
    
    /**
     * Gets refund_excl_vat
     * @return double
     */
    public function getRefundExclVat()
    {
        return $this->refund_excl_vat;
    }
  
    /**
     * Sets refund_excl_vat
     * @param double $refund_excl_vat 
     * @return $this
     */
    public function setRefundExclVat($refund_excl_vat)
    {
        
        $this->refund_excl_vat = $refund_excl_vat;
        return $this;
    }
    
    /**
     * Gets lines
     * @return \Swagger\Client\Model\ReturnLineViewModel[]
     */
    public function getLines()
    {
        return $this->lines;
    }
  
    /**
     * Sets lines
     * @param \Swagger\Client\Model\ReturnLineViewModel[] $lines 
     * @return $this
     */
    public function setLines($lines)
    {
        
        $this->lines = $lines;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
