<?php
/**
 * BackOrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChannelEngine\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChannelEngine\ApiClient;

/**
 * BackOrderTest Class Doc Comment
 *
 * @category    Class */
// * @description BackOrder
/**
 * @package     ChannelEngine\ApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BackOrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "BackOrder"
     */
    public function testBackOrder()
    {

    }

    /**
     * Test attribute "merchantBackorderNo"
     */
    public function testPropertyMerchantBackorderNo()
    {

    }

    /**
     * Test attribute "merchantOrderNo"
     */
    public function testPropertyMerchantOrderNo()
    {

    }

    /**
     * Test attribute "channelOrderNo"
     */
    public function testPropertyChannelOrderNo()
    {

    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {

    }

}
