<?php
/**
 * ChannelProductChangesResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChannelProductChangesResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description ChannelProductChangesResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelProductChangesResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ChannelProductChangesResponse"
     */
    public function testChannelProductChangesResponse()
    {

    }

    /**
     * Test attribute "to_be_created"
     */
    public function testPropertyToBeCreated()
    {

    }

    /**
     * Test attribute "to_be_updated"
     */
    public function testPropertyToBeUpdated()
    {

    }

    /**
     * Test attribute "to_be_removed"
     */
    public function testPropertyToBeRemoved()
    {

    }

}
