<?php
/**
 * ChannelProductResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChannelEngine\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChannelEngine\ApiClient;

/**
 * ChannelProductResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description ChannelProductResponse
/**
 * @package     ChannelEngine\ApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelProductResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ChannelProductResponse"
     */
    public function testChannelProductResponse()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "parentChannelReference"
     */
    public function testPropertyParentChannelReference()
    {

    }

    /**
     * Test attribute "mappedFields"
     */
    public function testPropertyMappedFields()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {

    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {

    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {

    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {

    }

    /**
     * Test attribute "manufacturerProductNumber"
     */
    public function testPropertyManufacturerProductNumber()
    {

    }

    /**
     * Test attribute "stock"
     */
    public function testPropertyStock()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "mSRP"
     */
    public function testPropertyMSRP()
    {

    }

    /**
     * Test attribute "purchasePrice"
     */
    public function testPropertyPurchasePrice()
    {

    }

    /**
     * Test attribute "vatRateType"
     */
    public function testPropertyVatRateType()
    {

    }

    /**
     * Test attribute "shippingCost"
     */
    public function testPropertyShippingCost()
    {

    }

    /**
     * Test attribute "shippingTime"
     */
    public function testPropertyShippingTime()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "imageUrl"
     */
    public function testPropertyImageUrl()
    {

    }

    /**
     * Test attribute "categoryTrail"
     */
    public function testPropertyCategoryTrail()
    {

    }

    /**
     * Test attribute "extraData"
     */
    public function testPropertyExtraData()
    {

    }

}
