<?php
/**
 * ChannelOrderRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChannelOrderRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description ChannelOrderRequest
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelOrderRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ChannelOrderRequest"
     */
    public function testChannelOrderRequest()
    {

    }

    /**
     * Test attribute "channel_reference"
     */
    public function testPropertyChannelReference()
    {

    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {

    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "company_registration_no"
     */
    public function testPropertyCompanyRegistrationNo()
    {

    }

    /**
     * Test attribute "vat_no"
     */
    public function testPropertyVatNo()
    {

    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {

    }

    /**
     * Test attribute "shipping_costs_incl_vat"
     */
    public function testPropertyShippingCostsInclVat()
    {

    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {

    }

    /**
     * Test attribute "order_date"
     */
    public function testPropertyOrderDate()
    {

    }

    /**
     * Test attribute "channel_customer_reference"
     */
    public function testPropertyChannelCustomerReference()
    {

    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {

    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {

    }

    /**
     * Test attribute "extra_data"
     */
    public function testPropertyExtraData()
    {

    }

}
