<?php
/**
 * MerchantShipmentTrackingRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChannelEngine\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChannelEngine\ApiClient;

/**
 * MerchantShipmentTrackingRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description MerchantShipmentTrackingRequest
/**
 * @package     ChannelEngine\ApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MerchantShipmentTrackingRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MerchantShipmentTrackingRequest"
     */
    public function testMerchantShipmentTrackingRequest()
    {

    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {

    }

    /**
     * Test attribute "trackTraceNo"
     */
    public function testPropertyTrackTraceNo()
    {

    }

    /**
     * Test attribute "trackTraceUrl"
     */
    public function testPropertyTrackTraceUrl()
    {

    }

}
