<?php
/**
 * OrderApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ChannelEngine\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelEngine API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ChannelEngine\ApiClient;

use \ChannelEngine\ApiClient\Configuration;
use \ChannelEngine\ApiClient\ApiClient;
use \ChannelEngine\ApiClient\ApiException;
use \ChannelEngine\ApiClient\ObjectSerializer;

/**
 * OrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  ChannelEngine\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for orderAcknowledge
     *
     * Merchant: Acknowledge Order.
     *
     */
    public function testOrderAcknowledge()
    {

    }

    /**
     * Test case for orderCreate
     *
     * Channel: Create Order.
     *
     */
    public function testOrderCreate()
    {

    }

    /**
     * Test case for orderGetNew
     *
     * Merchant: Get New Orders.
     *
     */
    public function testOrderGetNew()
    {

    }

    /**
     * Test case for orderInvoice
     *
     * Merchant: Download Invoice.
     *
     */
    public function testOrderInvoice()
    {

    }

    /**
     * Test case for orderPackingSlip
     *
     * Merchant: Download Packing Slip.
     *
     */
    public function testOrderPackingSlip()
    {

    }

}
